# Generated by Django 5.2.8 on 2025-11-29 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('des', 'تشریحی'), ('mcq', 'تستی')], max_length=4)),
                ('text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.exam')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال\u200cها',
            },
        ),
    ]
