# Generated by Django 5.2.8 on 2025-12-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classroom_staging'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='student_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
