# Generated by Django 5.2.8 on 2026-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_examassignment_score_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='is_cheated',
            field=models.BooleanField(default=False),
        ),
    ]
